version: '3'

services:
  db:
    image: mysql
    volumes:
      - ./docker/data:/var/lib/mysql/data
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql1234
      MYSQL_ROOT_PASSWORD: mysql1234
      MYSQL_DATABASE: go_db

  django:
    build:
      context: .
      dockerfile: ./desktop/restful-api-with-go/Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=samplesecret
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8080:8080"
    command: 
      - python manage.py runserver 0:8000
    volumes:
      - ./:/app/
